#!/bin/bash

# =====================================================
# SCRIPT TEST NOTIFIKASI LENGKAP
# =====================================================

echo "🔔 =============================================="
echo "🔔 TEST NOTIFIKASI FCM"
echo "🔔 =============================================="
echo ""

echo "📱 OPSI 1: Test via Firebase Console (Paling Mudah)"
echo "=============================================="
echo ""
echo "1. Ambil FCM Token dari app (login dulu!)"
echo "   Cek console log: 🔑 FCM TOKEN: [token]"
echo ""
echo "2. Buka Firebase Console:"
echo "   https://console.firebase.google.com/project/roasty-9b753/notification/compose"
echo ""
echo "3. Isi form:"
echo "   - Notification title: 🚚 Test Notifikasi"
echo "   - Notification text: Ini test dari Firebase Console"
echo "   - Target: Single device"
echo "   - FCM token: [paste token dari step 1]"
echo ""
echo "4. PENTING! Klik 'Additional options' → Tab 'Custom data'"
echo "   Tambahkan key-value:"
echo "   type = order_status"
echo "   resource_id = TEST-001"
echo "   target_screen = order_detail"
echo "   action = shipped"
echo ""
echo "5. Klik 'Test'"
echo ""
echo "✅ Notifikasi harusnya muncul di HP!"
echo ""
echo "=============================================="
echo ""

echo "📱 OPSI 2: Test via Edge Function (Otomatis)"
echo "=============================================="
echo ""
echo "1. Pastikan sudah login di app & FCM token tersimpan"
echo ""
echo "2. Jalankan SQL di Supabase SQL Editor:"
echo "   (Lihat file: QUICK_TEST_FCM.sql)"
echo ""
echo "3. Panggil Edge Function:"
echo ""
echo "curl https://fiyodlfgfbcnatebudut.supabase.co/functions/v1/send-push-notifications \\"
echo "  -H \"Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpeW9kbGZnZmJjbmF0ZWJ1ZHV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5OTQ0MDIsImV4cCI6MjA3ODU3MDQwMn0.pHruuh0dqQa3oUbwqYjbzEjzFiha0jFhcvO93DfkOlk\""
echo ""
echo "4. Expected response:"
echo '   {"success":true,"processed":1,"sent":1}'
echo ""
echo "✅ Notifikasi harusnya muncul di HP!"
echo ""
echo "=============================================="
echo ""

echo "❌ TROUBLESHOOTING"
echo "=============================================="
echo ""
echo "Jika notifikasi TIDAK muncul:"
echo ""
echo "1. CEK TOKEN TERSIMPAN:"
echo "   SELECT * FROM fcm_tokens WHERE is_active = true;"
echo "   → Harus ada minimal 1 row"
echo ""
echo "2. CEK EDGE FUNCTION SECRET:"
echo "   → Buka Supabase Dashboard → Settings → Edge Functions → Secrets"
echo "   → Cek apakah FIREBASE_SERVICE_ACCOUNT sudah di-set"
echo "   → Jika belum: lihat SETUP_FCM_SERVER_KEY.md"
echo ""
echo "3. CEK LOG EDGE FUNCTION:"
echo "   → Buka Supabase Dashboard → Edge Functions → Logs"
echo "   → Cari error message"
echo ""
echo "4. CEK APP LOG:"
echo "   → Pastikan ada log: 🔑 FCM TOKEN: [token]"
echo "   → Pastikan ada log: ✅ FCM token saved to Supabase"
echo ""
echo "5. REBUILD APP:"
echo "   flutter clean && flutter run"
echo ""
echo "=============================================="
