// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYOAC-5FD2M-kxU2z5q_aASxfyFkNQL2c',
    appId: '1:448359207392:web:cfae0e6c20ffa73429db85',
    messagingSenderId: '448359207392',
    projectId: 'modul6-61b6f',
    authDomain: 'modul6-61b6f.firebaseapp.com',
    storageBucket: 'modul6-61b6f.firebasestorage.app',
    measurementId: 'G-03XDSR0W0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKFaK8KnjMIYbYKUzQJ71QUEY0sK1kduQ',
    appId: '1:448359207392:android:da5ed600c0d8493329db85',
    messagingSenderId: '448359207392',
    projectId: 'modul6-61b6f',
    storageBucket: 'modul6-61b6f.firebasestorage.app',
  );
}
